-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 17:17:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Grocerwala
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Grocerwala
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Grocerwala` DEFAULT CHARACTER SET utf8 ;
USE `Grocerwala` ;

-- -----------------------------------------------------
-- Table `Grocerwala`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grocerwala`.`User` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_name` VARCHAR(45) NOT NULL,
  `u_email` VARCHAR(30) NOT NULL,
  `u_phone` VARCHAR(13) NOT NULL,
  `u_address` VARCHAR(250) NOT NULL,
  `roles` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) GENERATED ALWAYS AS () STORED,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grocerwala`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grocerwala`.`category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grocerwala`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grocerwala`.`Items` (
  `admin_id` INT NOT NULL,
  `i_id` INT NOT NULL AUTO_INCREMENT,
  `i_name` VARCHAR(45) NOT NULL,
  `i_price` DOUBLE NOT NULL,
  `i_description` VARCHAR(250) NULL,
  `i_stock` INT NOT NULL,
  `manufacture_date` DATE NOT NULL,
  `categoryid` INT NULL,
  PRIMARY KEY (`i_id`, `i_name`, `i_price`),
  INDEX `customerid_idx` (`admin_id` ASC) VISIBLE,
  INDEX `categoryid_idx` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `customerid`
    FOREIGN KEY (`admin_id`)
    REFERENCES `Grocerwala`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoryid`
    FOREIGN KEY (`categoryid`)
    REFERENCES `Grocerwala`.`category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grocerwala`.`Order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grocerwala`.`Order_details` (
  `ouser_id` INT NOT NULL,
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `Delivery_charges` FLOAT NOT NULL,
  `delivery_date_time` DATETIME NOT NULL,
  `service_charges` FLOAT NOT NULL,
  `Item_qty` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `ocustid_idx` (`ouser_id` ASC) VISIBLE,
  CONSTRAINT `ocustid`
    FOREIGN KEY (`ouser_id`)
    REFERENCES `Grocerwala`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grocerwala`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grocerwala`.`feedback` (
  `user_id` INT NOT NULL,
  `description` VARCHAR(250) NULL,
  `rating` FLOAT NULL,
  INDEX `cust_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `cust_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Grocerwala`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
